#!/bin/bash

echo -e "Default \e[35m"
lagi='y'
while [ $lagi == 'y' ] || [ $lagi == 'Y' ];
do
clear
echo "========================================================";
echo "                  WELCOME SELLER VPS                ]---";
echo "------------------------------------------------------- ";
echo "#  aliyahaura02 / khorul : 089697708638/087823060548   #";
echo "#  facebook   : https://m.facebook.com/aliyahaura02    #";
echo "#                (fb.com/khoirulanam)                  #";
echo "#                             Copyright seller.vps.net #";
echo "========================================================";
sudo ./bash/view.sh
sudo date
echo -e "Default \e[96m"
echo "1) Buat user";                 
echo "2) Buat user Trial";
echo "3) Perbarui user";
echo "4) Semua user ";
echo "5) Hapus user";
echo "6) Monitor user Login";
echo "7) Daftar user Aktif";
echo "8) Restart Dropbear ";
echo "9) Restart Openssh ";
echo "10) Restart Openvpn ";
echo "11) Restart Squid3 ";
echo "12) Restart Webmin ";
echo "13) Restart VPS";
echo "14) Memory Usage (ps-mem)";
echo "15) Speedtest ";
echo "16) Benchmark (benchmark)";
echo "17) auto expired user  ";
echo "18) GaNti banner";
echo "19) Bersihkan Cache Ram";
echo "20) Ganti Paswod VPS";
echo "21) User Expired";
echo "22) Ganti Port Openssh";
echo "23) Ganti Port OpenVpn ";
echo "24) Ganti Port  Dropbear";
echo "25) Ganti Port  Squid3";
echo "";
echo "";
echo "26) Exit";
echo "=======================================================";
echo "";
echo "";
echo "";
read -p "Silahkan Ktik nomer Pilihan Anda Lalu Tekan ENTER : " pil;
echo "";

case $pil in
1)  sudo ./bash/usernew

    ;;
2)   sudo ./bash/trial
   
    ;;
3)   sudo ./bash/renew

    ;;
4)   sudo ./bash/userlist

    ;; 
5)   sudo ./bash/userdelete.sh
   
   ;;
6)   sudo ./bash/user-login.sh
   
   ;;
7)   sudo ./bash/userlist
   
   ;;   
8)   sudo ./bash/dropbear
   
   ;;
9)   sudo ./bash/openssh
   
   ;;  
10)   sudo ./bash/openvpn
   
   ;;
11)   sudo ./bash/squid3
   
   ;;
12)   sudo ./bash/webmin
   
   ;;
13)   sudo ./bash/rebootserver
   
   ;;
14)   sudo ./bash/ps_mem.py
   
   ;;
15)   sudo ./bash/speedtest_cli.py
   
   ;;
16)   sudo ./bash/bench-network.sh
   
   ;;
17)  sudo ./bash/autoexpired.sh

    ;;
18)   sudo ./bash/bannerlogin
   
    ;;
19)   sudo ./bash/cacheram

    ;;
20)   sudo ./bash/password

    ;; 
21)   sudo ./bash/user-expired.sh
   
   ;;
22)   sudo ./bash/portopenssh
   
   ;;
23)   sudo ./bash/portopenvpn
   
   ;;   
24)   sudo ./bash/portdropbear
   
   ;;
25)   sudo ./bash/portsquid3
   
   ;;  
26)    exit
    ;;
*)    echo "Maaf, Pilihan Tidak tersedia"
esac
echo ""
echo "DEVELOPED BY akiyahaura02 (fb.com/aliyahaura02, 089697708638)"
echo ""
echo -n "Ingin Lanjut ke Pilhan Yang Lain? [y/n]: ";
read lagi;
while [ $lagi != 'y' ] && [ $lagi != 'Y' ] && [ $lagi != 'n' ] && [ $lagi != 'N' ];
do
echo "Maaf, input yang anda masukkan salah";
echo -n "Ingin Lanjut ke Program Yang Lain? [y/n]: ";
read lagi;
done
done
